[package]
name = "cc-lb-property-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
autotests = false

[[test]]
name = "integration"
path = "tests/all.rs"

[dependencies]
cc-lb-domain.workspace = true
bytes.workspace = true
cc-lb-control.workspace = true
cc-lb-engine = { path = "../../crates/cc-lb-engine" }
cc-lb-routing.workspace = true
http.workspace = true
proptest.workspace = true
