[package]
name = "tests-loom"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
autotests = false

[[test]]
name = "integration"
path = "tests/all.rs"

[lib]
name = "cc_lb_loom_tests"

[dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }

[target.'cfg(loom)'.dependencies]
loom = "0.7"
