[package]
name = "tests-loom"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "cc_lb_loom_tests"

[dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }

[target.'cfg(loom)'.dependencies]
loom = "0.7"

arc-swap.workspace = true
cc-lb-storage-api = { path = "../../crates/cc-lb-storage-api" }
cc-lb-storage-redb = { path = "../../crates/cc-lb-storage-redb" }
dashmap.workspace = true
globset.workspace = true
metrics.workspace = true
serde = { workspace = true, features = ["derive"] }
parking_lot = "0.12"
bincode = "2"
