[package]
name = "cache-aware-router"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
cc-lb-plugin-wire = { path = "../../../crates/cc-lb-plugin-wire" }
uuid = { version = "1", default-features = false, features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
extism-pdk = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
