/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpstreamsRouteImport } from './routes/upstreams'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrincipalsRouteImport } from './routes/principals'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const UpstreamsRoute = UpstreamsRouteImport.update({
  id: '/upstreams',
  path: '/upstreams',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalsRoute = PrincipalsRouteImport.update({
  id: '/principals',
  path: '/principals',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/principals': typeof PrincipalsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/upstreams': typeof UpstreamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/principals': typeof PrincipalsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/upstreams': typeof UpstreamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/config': typeof ConfigRoute
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/plugins': typeof PluginsRoute
  '/principals': typeof PrincipalsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/upstreams': typeof UpstreamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/plugins'
    | '/principals'
    | '/settings'
    | '/status'
    | '/upstreams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/plugins'
    | '/principals'
    | '/settings'
    | '/status'
    | '/upstreams'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/plugins'
    | '/principals'
    | '/settings'
    | '/status'
    | '/upstreams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ConfigRoute: typeof ConfigRoute
  CredentialsRoute: typeof CredentialsRoute
  LogsRoute: typeof LogsRoute
  PluginsRoute: typeof PluginsRoute
  PrincipalsRoute: typeof PrincipalsRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  UpstreamsRoute: typeof UpstreamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upstreams': {
      id: '/upstreams'
      path: '/upstreams'
      fullPath: '/upstreams'
      preLoaderRoute: typeof UpstreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principals': {
      id: '/principals'
      path: '/principals'
      fullPath: '/principals'
      preLoaderRoute: typeof PrincipalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ConfigRoute: ConfigRoute,
  CredentialsRoute: CredentialsRoute,
  LogsRoute: LogsRoute,
  PluginsRoute: PluginsRoute,
  PrincipalsRoute: PrincipalsRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  UpstreamsRoute: UpstreamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
