[package]
name = "plugin-internal-key-mapping"
version = "0.1.0"
edition = "2021"
publish = false
license.workspace = true

[lib]
name = "plugin_internal_key_mapping"
crate-type = ["cdylib"]

[dependencies]
base64.workspace = true
extism-pdk = { path = "../plugin-api-key/extism-pdk", version = "=1.21.0" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
extism.workspace = true
serde_json.workspace = true
