[package]
name = "cc-lb-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
cc-lb-engine = { path = "../crates/cc-lb-engine" }

http = "1"
libfuzzer-sys = "0.4"

[[bin]]
name = "header_parser"
path = "fuzz_targets/header_parser.rs"
test = false
doc = false
bench = false
