[package]
name = "cc-lb-contract"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
cc-lb-plugin-api = { workspace = true }
cc-lb-storage-api = { version = "0.1.0", path = "../cc-lb-storage-api" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
