[package]
name = "cc-lb-dialect-bedrock"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
aws-eventstream-codec = { path = "../aws-eventstream-codec" }
bytes.workspace = true
cc-lb-plugin-api = { path = "../cc-lb-plugin-api" }
http.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
insta.workspace = true
axum.workspace = true
fake-bedrock-runtime = { path = "../../tests/fixtures/fake-bedrock-runtime" }
http-body-util.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
tower = { workspace = true, features = ["util"] }
