use cc_lb_bdd_tests::{W1ObservableSpec, W1ScenarioEvidence, bdd_scenario};

macro_rules! assert_w1_evidence {
    ($ctx:ident, $evidence:ident) => {{
        let evidence: W1ScenarioEvidence = $evidence;
        $ctx.assert(
            evidence.is_satisfied(),
            format!(
                "{}: expected={}, actual={}",
                evidence.observable,
                evidence.expected_summary(),
                evidence.actual_summary()
            ),
        );
    }};
}

mod w1_f1 {
    use super::*;

    bdd_scenario! { id: "F1.1a", fn_name: fast_f1_1a, persona: Alice, title: "New team registration finishes active state and the first key on one screen", description: "Alice registers a new team and the harness records the active principal and first key observable through storage audit and request evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.1a", "F1", "registration_active_first_key", "first-key-visible-once", 201)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.1b", fn_name: fast_f1_1b, persona: Alice, title: "New team registration records who created it and when in audit", description: "Alice registers a new team and the harness records creator and time evidence in the audit stream for later review.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.1b", "F1", "registration_audit_creator_time", "creator-time-audit", 201)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.2", fn_name: f1_2, persona: Alice, title: "An issued key is shown only once right after registration", description: "Alice leaves the first key screen and the harness records that only preview metadata remains after the one-time secret display.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.2", "F1", "first_secret_display_once", "secret-preview-only", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.3", fn_name: f1_3, persona: Alice, title: "A second save stops if another operator changed the same team meanwhile", description: "Alice saves from a stale team view and the harness records a conflict observable that requires reloading the latest principal state.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.3", "F1", "stale_save_conflict", "reload-latest-values", 409)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.4", fn_name: fast_f1_4, persona: Alice, title: "Calls from an inactive team are not accepted", description: "Alice deactivates a team and the harness records the paused-team rejection observable with usage and audit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.4", "F1", "inactive_team_rejection", "team-paused", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.5", fn_name: fast_f1_5, persona: Alice, title: "Calls outside the model range allowed for a team are rejected", description: "Alice restricts a team to a model bundle and the harness records the disallowed model rejection observable.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.5", "F1", "model_acl_rejection", "model-not-allowed", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.7", fn_name: fast_f1_7, persona: Alice, title: "Deleting a team does not erase audit traces of what that team did", description: "Alice deletes a team and the harness records retained audit evidence for deleted-team review.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.7", "F1", "deleted_team_audit_retained", "deleted-team-audit", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.8", fn_name: f1_8, persona: Alice, title: "Registration is rejected when an identifier contains forbidden characters or a reserved prefix", description: "Alice submits a reserved or invisible team identifier and the harness records a validation rejection without usage impact.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.8", "F1", "invalid_identifier_rejection", "reserved-or-invisible-name", 400)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.10", fn_name: f1_10, persona: Alice, title: "When an inactive team is restored to active, the same secrets are soon accepted again", description: "Alice reactivates a paused team and the harness records restored acceptance with paired status-change audit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.10", "F1", "reactivated_team_acceptance", "same-secret-restored", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F1.11", fn_name: f1_11, persona: Alice, title: "Calls started just before deactivation finish, and only new calls are rejected", description: "Alice deactivates during active traffic and the harness records separated before and after deactivation observables.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F1.11", "F1", "deactivation_boundary_split", "before-after-deactivation", 202)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
}

mod w1_f2 {
    use super::*;

    bdd_scenario! { id: "F2.1", fn_name: fast_f2_1, persona: Alice, title: "When a new key is issued, the secret is shown only once", description: "Alice issues a client key and the harness records one-time full secret exposure plus durable preview metadata.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.1", "F2", "key_secret_display_once", "full-secret-once", 201)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.2", fn_name: f2_2, persona: Alice, title: "During key rotation, the new key and old key have a short overlap period", description: "Alice rotates a key and the harness records the new secret plus short overlap observable for the old key.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.2", "F2", "key_rotation_overlap", "old-new-overlap", 201)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.3", fn_name: fast_f2_3, persona: Alice, title: "Immediately after key revocation, the next calls are rejected", description: "Alice revokes a key and the harness records immediate rejection plus revocation audit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.3", "F2", "revoked_key_rejection", "key-no-longer-accepted", 401)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.4a", fn_name: f2_4a, persona: Alice, title: "A key that automatically expires at a set time stops at that time", description: "Alice sets key expiry and the harness records expired-key rejection evidence at the cutoff point.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.4a", "F2", "expired_key_rejection", "expiry-cutoff", 401)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.4b", fn_name: f2_4b, persona: Alice, title: "An upcoming-expiration notification reaches the operator in advance", description: "Alice configures key expiry and the harness records advance notification delivery plus audit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.4b", "F2", "key_expiry_notice", "advance-expiry-notice", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.5", fn_name: fast_f2_5, persona: Alice, title: "Secrets are never shown on the key list screen", description: "Alice opens the key list and the harness records secret-free list evidence with holder and last-used metadata only.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.5", "F2", "key_list_secret_hidden", "no-secret-in-list", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.6", fn_name: f2_6, persona: Alice, title: "An operator can later edit a key holder name and memo", description: "Alice edits key holder metadata and the harness records immediate list reflection with old and new audit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.6", "F2", "key_holder_metadata_update", "holder-memo-updated", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.8a", fn_name: f2_8a, persona: Alice, title: "Usage reporting separates call counts and rejection reasons by key holder", description: "Alice views holder usage and the harness records per-holder call and rejection reason evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.8a", "F2", "holder_usage_breakdown", "per-holder-usage", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.8b", fn_name: f2_8b, persona: Alice, title: "When a holder name is edited, old usage is unified under the new name", description: "Alice renames a holder and the harness records unified past and new usage under the updated holder label.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.8b", "F2", "renamed_holder_usage_unified", "new-holder-unifies-usage", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.10", fn_name: f2_10, persona: Alice, title: "The number of active keys one holder may have at the same time is limited", description: "Alice enforces active key count per holder and the harness records rejection until an old key is revoked.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.10", "F2", "holder_active_key_limit", "active-key-limit", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.11", fn_name: f2_11, persona: Alice, title: "Looking again at the last few characters of a key is also audited", description: "Alice views a key preview and the harness records an audit row that excludes the full secret.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.11", "F2", "key_preview_view_audited", "last-four-audit", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.12a", fn_name: f2_12a, persona: Alice, title: "The list screen clearly distinguishes whether a key holder is a person or a machine", description: "Alice opens the key list and the harness records person and machine holder classification evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.12a", "F2", "holder_kind_visible", "person-machine-holder", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.12b", fn_name: f2_12b, persona: Alice, title: "Usage reporting also shows separate totals for person and machine units", description: "Alice views usage and the harness records separate person and machine holder totals in the report evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.12b", "F2", "holder_kind_usage_totals", "person-machine-totals", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.13a", fn_name: f2_13a, persona: Alice, title: "Key state is handled in active to suspended to revoked order", description: "Alice moves a key through active, suspended, and revoked states and the harness records ordered state evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.13a", "F2", "key_state_order", "active-suspended-revoked", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.13b", fn_name: f2_13b, persona: Alice, title: "Every key state transition records who changed it and when in audit", description: "Alice changes key state and the harness records transition actor and time evidence for audit reconstruction.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.13b", "F2", "key_state_transition_audit", "transition-audit-flow", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F2.14", fn_name: f2_14, persona: Alice, title: "Trying key rotation on a storage backend that does not support rotation is politely rejected", description: "Alice tries unsupported rotation and the harness records graceful rejection plus audit evidence for the attempted operation.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F2.14", "F2", "unsupported_rotation_rejection", "rotation-not-supported", 400)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
}

mod w1_f3 {
    use super::*;

    bdd_scenario! { id: "F3.1", fn_name: fast_f3_1, persona: Bob, title: "Calling a normal model with a normal key returns the response unchanged", description: "Bob sends a normal model call and the harness records unchanged response and successful usage evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.1", "F3", "normal_call_success", "unchanged-response", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.2", fn_name: f3_2, persona: Bob, title: "A streaming response flows to the end without interruption", description: "Bob sends a streaming call and the harness records ordered stream pieces and terminal marker evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.2", "F3", "streaming_success", "stream-terminal", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.3", fn_name: fast_f3_3, persona: Bob, title: "A call sent with an unknown key is politely rejected", description: "Bob sends an unknown key and the harness records Claude-shaped invalid key rejection evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.3", "F3", "unknown_key_rejection", "invalid-key-envelope", 401)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.4", fn_name: fast_f3_4, persona: Bob, title: "A call sent with a key from an inactive team is rejected", description: "Bob calls with an inactive team key and the harness records paused principal rejection evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.4", "F3", "inactive_key_rejection", "inactive-principal-envelope", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.5a", fn_name: f3_5a, persona: Bob, title: "Calling a model not allowed for the caller's team rejects the call", description: "Bob calls outside the model bundle and the harness records the disallowed model rejection observable.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.5a", "F3", "disallowed_model_rejection", "model-bundle-block", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.5b", fn_name: f3_5b, persona: Bob, title: "A disallowed-model rejection message is delivered as a Claude-shaped error envelope", description: "Bob receives a disallowed-model envelope and the harness records message and shape evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.5b", "F3", "disallowed_model_error_shape", "claude-error-envelope", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.5c", fn_name: f3_5c, persona: Bob, title: "A disallowed-model rejection is added to both usage reporting and the audit bundle", description: "Bob triggers a model rejection and the harness records both usage and audit bundle evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.5c", "F3", "disallowed_model_usage_audit", "usage-audit-disallowed-model", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.8", fn_name: f3_8, persona: Bob, title: "If a sudden problem occurs inside cc-lb during a response, it closes with a Claude-shaped error", description: "Bob experiences an interrupted response and the harness records a Claude-shaped midway interruption evidence row.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.8", "F3", "mid_response_error_envelope", "interrupted-midway", 500)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.9", fn_name: f3_9, persona: Bob, title: "Bob completes the upload, download, and delete file flow through cc-lb", description: "Bob runs the file lifecycle and the harness records consistent file identifier evidence for upload, download, and delete.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.9", "F3", "file_lifecycle_flow", "same-file-id", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.11a", fn_name: f3_11a, persona: Bob, title: "A call sent to an unknown path or unknown action returns a Claude-shaped error envelope", description: "Bob calls an unknown operation and the harness records recognized error envelope evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.11a", "F3", "unknown_operation_error_shape", "path-operation-not-recognized", 404)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.11b", fn_name: f3_11b, persona: Bob, title: "Rejection of an unknown path or action is added to usage reporting by rejection reason type", description: "Bob triggers an unknown operation rejection and the harness records rejection reason usage trend evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.11b", "F3", "unknown_operation_usage_reason", "unknown-operation-reason", 404)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.12", fn_name: f3_12, persona: Bob, title: "When rejected by a limit, the same response includes when to try again", description: "Bob hits a temporary limit and the harness records retry guidance evidence in the rejection response.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.12", "F3", "limit_retry_guidance", "retry-after-guidance", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.13", fn_name: f3_13, persona: Bob, title: "If the response body exceeds a predefined ceiling, it is politely cut off", description: "Bob receives an oversized response and the harness records cutoff and cap exceeded evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.13", "F3", "response_body_cap_cutoff", "cap-exceeded", 413)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.14", fn_name: f3_14, persona: Bob, title: "Attempts to go directly to an external host outside registered paths are blocked", description: "Bob attempts an unregistered external exit and the harness records tunnel enforcement evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.14", "F3", "external_tunnel_enforced", "registered-tunnel-only", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.15", fn_name: f3_15, persona: Bob, title: "Single-hop forwarding markers are cleaned up at the response boundary", description: "Bob receives a response and the harness records response boundary cleanup evidence for normal and error envelopes.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.15", "F3", "hop_header_cleanup", "response-boundary-clean", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F3.16", fn_name: f3_16, persona: Bob, title: "Temporarily turning off authentication in an isolated test environment is clearly marked", description: "Bob calls in isolated no-auth mode and the harness records the disabled authentication marker evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F3.16", "F3", "auth_disabled_test_marker", "auth-disabled-banner", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
}

mod w1_f4 {
    use super::*;

    bdd_scenario! { id: "F4.1a", fn_name: f4_1a, persona: Alice, title: "Yesterday's highest-usage teams are visible at a glance in cost order", description: "Alice opens the dashboard and the harness records cost ordered top-team evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.1a", "F4", "dashboard_top_teams_cost_order", "cost-order-top-teams", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.1b", fn_name: f4_1b, persona: Alice, title: "The same table shows call count and rejection ratio together", description: "Alice views the same dashboard table and the harness records call count plus rejection ratio evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.1b", "F4", "dashboard_call_rejection_ratio", "calls-rejections-same-row", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.1c", fn_name: f4_1c, persona: Alice, title: "Pressing a team row leads to that team's detail view", description: "Alice presses a team row and verifies visual navigation to that team's detail view.", oos_manual: "Clicking a team row requires human click and visual confirmation of UI page transition; replacing it with storage assertions distorts the UX intent.", given: |ctx| { ctx.scenario_id() }, when: |scenario| { scenario }, then: |scenario, ctx| { let _ = (scenario, ctx); }, }
    bdd_scenario! { id: "F4.2", fn_name: f4_2, persona: Alice, title: "Alice narrows the view by period, team, key holder, or model", description: "Alice applies dashboard filters and the harness records recalculated cost, call count, and rejection ratio evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.2", "F4", "dashboard_filter_recalculation", "period-team-holder-model", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.3", fn_name: f4_3, persona: Alice, title: "When monthly cost approaches a configured limit, it appears early on the same screen", description: "Alice views a near-limit team and the harness records early monthly cost warning evidence before rejection.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.3", "F4", "monthly_cost_near_limit_notice", "near-limit-warning", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.4a", fn_name: f4_4a, persona: Alice, title: "Call share and cost share by model are visible at a glance on the same screen", description: "Alice views model share and the harness records call share plus cost share evidence by model.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.4a", "F4", "model_share_cost_share", "model-share", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.4b", fn_name: f4_4b, persona: Alice, title: "Pressing a model in the model share table leads to its hourly flow", description: "Alice selects a model and the harness records model trend navigation evidence at the data level.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.4b", "F4", "model_trend_navigation", "model-hourly-flow", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.5", fn_name: f4_5, persona: Alice, title: "Hourly usage flow continues without gaps", description: "Alice views a daily trend and the harness records continuous period evidence including explicit zero periods.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.5", "F4", "usage_trend_without_gaps", "zero-periods-visible", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.6", fn_name: f4_6, persona: Alice, title: "Rejection reasons are visible at a glance by type", description: "Alice views rejections and the harness records grouped rejection reason evidence with ratios and trend markers.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.6", "F4", "rejection_reasons_grouped", "largest-reason-first", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.7", fn_name: f4_7, persona: Alice, title: "A report screen can be downloaded in table format", description: "Alice downloads a filtered report and the harness records table-format export evidence without secrets.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.7", "F4", "report_table_export", "secret-free-table", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.8", fn_name: f4_8, persona: Alice, title: "The fact that the live flow was interrupted is clearly visible on the same screen", description: "Alice sees a live flow interruption and the harness records interruption marker and accurate accumulated report evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.8", "F4", "live_flow_interruption_marker", "stream-interrupted", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.10", fn_name: f4_10, persona: Alice, title: "Alice narrows the log page by type, team, or holder", description: "Alice filters logs and the harness records matching rows without secret exposure and stable filter evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.10", "F4", "log_filter_secret_free", "type-team-holder-filter", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.11a", fn_name: f4_11a, persona: Alice, title: "Zero calls and not known yet are clearly distinguished in the same table", description: "Alice views report periods and the harness records separate zero-call and unknown markers in table evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.11a", "F4", "zero_vs_unknown_table_markers", "zero-and-unknown", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.11b", fn_name: f4_11b, persona: Alice, title: "The meaning of the two markers is explained with user-facing help", description: "Alice reads help explaining zero-call and not-known markers in the same table.", oos_manual: "User cognitive tooltip requires human inspection of readability and badge guidance; automated DOM checks alone do not preserve the scenario intent.", given: |ctx| { ctx.scenario_id() }, when: |scenario| { scenario }, then: |scenario, ctx| { let _ = (scenario, ctx); }, }
    bdd_scenario! { id: "F4.11c", fn_name: f4_11c, persona: Alice, title: "The same distinction is also shown on the hourly flow chart", description: "Alice views the time-period trend and the harness records separate zero-call and unknown chart marker evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.11c", "F4", "zero_vs_unknown_chart_markers", "trend-marker-legend", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F4.12", fn_name: f4_12, persona: Alice, title: "Alice views the per-stage dwell time of one call in detail", description: "Alice opens a slow call detail and the harness records per-stage timing evidence with the slowest stage highlighted.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F4.12", "F4", "call_stage_latency_detail", "slowest-stage-highlight", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
}

mod w1_f6 {
    use super::*;

    bdd_scenario! { id: "F6.1", fn_name: f6_1, persona: Alice, title: "When the per-minute limit is exceeded, the team's next call is temporarily rejected", description: "Alice sets a per-minute limit and the harness records temporary retry-shortly rejection evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.1", "F6", "per_minute_limit_rejection", "retry-shortly", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.2a", fn_name: f6_2a, persona: Alice, title: "When the daily limit fills, the rest of that day's calls are rejected and it resets at the same time next day", description: "Alice sets a daily limit and the harness records daily exhaustion and next-day reset evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.2a", "F6", "daily_limit_reset", "next-day-reset", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.2b", fn_name: f6_2b, persona: Alice, title: "Daily-limit rejection guidance includes when the limit will clear again", description: "Alice configures daily limits and the harness records reset-time guidance evidence for Bob.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.2b", "F6", "daily_limit_reset_guidance", "reset-time-guidance", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.3", fn_name: f6_3, persona: Alice, title: "When the monthly cost limit approaches, new calls are rejected early", description: "Alice sets a monthly cost limit and the harness records early rejection plus dashboard warning evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.3", "F6", "monthly_cost_early_rejection", "monthly-limit-near", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.4", fn_name: f6_4, persona: Alice, title: "Calling outside the allowed model bundle is rejected", description: "Alice restricts a model bundle and the harness records persistent disallowed model evidence until the bundle changes.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.4", "F6", "model_bundle_enforcement", "disallowed-model", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.5", fn_name: f6_5, persona: Alice, title: "A call immediately after a limit edit soon reflects the new limit", description: "Alice edits a limit and the harness records immediate new-limit acceptance plus audit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.5", "F6", "limit_edit_immediate_effect", "new-limit-active", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.8", fn_name: f6_8, persona: Alice, title: "Limit violations appear separately in reporting by rejection reason type", description: "Alice views limit reports and the harness records separate per-minute, daily, monthly, and model rejection evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.8", "F6", "limit_rejection_reason_groups", "limit-types-separated", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.9", fn_name: f6_9, persona: Alice, title: "cc-lb does not go to external hosts outside the allow list", description: "Alice observes external host enforcement and the harness records blocked host evidence with audit details.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.9", "F6", "external_host_allowlist_block", "host-not-allowed", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.10a", fn_name: f6_10a, persona: Alice, title: "The body-size limit for a specific path applies to calls on that path", description: "Alice sets a path body-size limit and the harness records body limit exceeded evidence for that path.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.10a", "F6", "path_body_limit_rejection", "body-size-exceeded", 413)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.10b", fn_name: f6_10b, persona: Alice, title: "Changing the body limit for one path does not affect the body limit for another path", description: "Alice changes one path limit and the harness records unaffected acceptance evidence on another path.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.10b", "F6", "path_body_limit_isolation", "other-path-unaffected", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.12", fn_name: f6_12, persona: Alice, title: "A team temporarily rejected for a limit violation recovers after time passes", description: "Alice observes per-minute recovery and the harness records same-key acceptance after recovery evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.12", "F6", "temporary_limit_recovery", "same-key-recovered", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.13", fn_name: f6_13, persona: Alice, title: "A team that used up its daily limit is automatically accepted again at the same time next day", description: "Alice observes daily recovery and the harness records next-day automatic acceptance evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.13", "F6", "daily_limit_auto_recovery", "daily-recovery", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.14a", fn_name: f6_14a, persona: Alice, title: "One team's per-minute limit violation does not affect another team's call acceptance", description: "Alice compares two teams and the harness records independent team limit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.14a", "F6", "team_limit_isolation", "other-team-accepted", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.14b", fn_name: f6_14b, persona: Alice, title: "One team's surge does not delay another team's recovery point", description: "Alice observes separate recovery timing and the harness records that another team's recovery point remains unchanged.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.14b", "F6", "team_recovery_time_isolation", "recovery-not-delayed", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.15", fn_name: f6_15, persona: Alice, title: "A separate limit can be set on the number of calls being processed at the same time", description: "Alice sets a concurrency limit and the harness records concurrent call rejection and immediate recovery evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.15", "F6", "concurrent_call_limit", "concurrent-limit-reached", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.16", fn_name: f6_16, persona: Alice, title: "The enforcement unit changes depending on whether the limit targets team, holder, or key", description: "Alice selects holder scope and the harness records scoped rejection evidence isolated from other holders.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.16", "F6", "limit_scope_holder", "scope-visible", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F6.17", fn_name: f6_17, persona: Alice, title: "A smaller limit can be set separately for only one key", description: "Alice sets a per-key override and the harness records smaller key limit evidence with audit details.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F6.17", "F6", "per_key_limit_override", "smaller-key-limit", 429)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
}

mod w1_f19 {
    use super::*;

    bdd_scenario! { id: "F19.1", fn_name: f19_1, persona: Alice, title: "Calls with the same meaning converge to the same place on the second call", description: "Alice reviews cache affinity and the harness records same semantic input routed to the same processing path.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.1", "F19", "cache_affinity_same_path", "same-processing-path", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.2", fn_name: f19_2, persona: Alice, title: "Cache hit rate is visible at a glance on the same screen", description: "Alice views cache hit rate and the harness records hit rate trend plus cost savings evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.2", "F19", "cache_hit_rate_visible", "hit-rate-trend", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.3a", fn_name: f19_3a, persona: Alice, title: "Cost saved through cache hits is shown separately in cost reporting", description: "Alice views cost reporting and the harness records separate cache savings evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.3a", "F19", "cache_cost_saved_separate", "cache-savings", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.3b", fn_name: f19_3b, persona: Alice, title: "Cost without cache is also shown with a virtual cost label", description: "Alice views virtual cost and the harness records clearly distinguished actual and no-cache cost evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.3b", "F19", "cache_virtual_cost_label", "without-cache-cost", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.3c", fn_name: f19_3c, persona: Alice, title: "Actual cost and virtual cost are compared as an hourly flow", description: "Alice views hourly cache cost comparison and the harness records greatest-difference trend evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.3c", "F19", "cache_cost_hourly_comparison", "actual-vs-virtual", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.4", fn_name: f19_4, persona: Alice, title: "When cache affinity breaks, the call is processed as new", description: "Alice observes a cache miss and the harness records fresh processing plus hit-rate drop evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.4", "F19", "cache_affinity_break_fresh", "fresh-processing", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.5", fn_name: f19_5, persona: Alice, title: "Cache affinity does not cross team boundaries", description: "Alice compares two teams and the harness records team-separated cache savings and audit evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.5", "F19", "cache_team_boundary", "per-team-cache", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.6a", fn_name: f19_6a, persona: Alice, title: "Even while cache affinity works, limit and model bundle violations are still rejected", description: "Alice observes cache affinity with a violation and the harness records rejection not bypassed by cache evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.6a", "F19", "cache_does_not_bypass_limits", "violation-still-rejected", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.6b", fn_name: f19_6b, persona: Alice, title: "Cache hit rate is calculated excluding rejected calls", description: "Alice views hit rate and the harness records rejected calls excluded from cache rate evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.6b", "F19", "cache_hit_rate_excludes_rejections", "accepted-only-hit-rate", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.7", fn_name: f19_7, persona: Alice, title: "Short-lived cache and long-lived cache appear separated by tier", description: "Alice views cache tiers and the harness records separate short and long tier evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.7", "F19", "cache_tiers_separated", "short-long-tier", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.8", fn_name: f19_8, persona: Alice, title: "Calls from an inactive team are not accepted even through a cache hit", description: "Alice deactivates a cache-friendly team and the harness records cache not acting as bypass evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.8", "F19", "inactive_team_cache_block", "cache-no-bypass", 403)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.9", fn_name: f19_9, persona: Alice, title: "One call's cache state is visible at a glance with clear classification", description: "Alice opens cache detail and the harness records hit, miss, partial, create, skip, and unknown classification evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.9", "F19", "cache_state_classification", "hit-miss-partial-create-skip-unknown", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F19.10", fn_name: f19_10, persona: Alice, title: "When a cache hit has a cost unit mismatch from the first call, it is marked separately", description: "Alice views token mismatch and the harness records mismatch marker plus cost impact evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F19.10", "F19", "cache_token_mismatch_marker", "token-mismatch", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
}

mod w1_f26 {
    use super::*;

    bdd_scenario! { id: "F26.1", fn_name: fast_f26_1, persona: Charlie, title: "Liveness and readiness to process are shown separately", description: "Charlie checks health and the harness records separate liveness and readiness evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.1", "F26", "liveness_readiness_separate", "live-ready-separated", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.2a", fn_name: f26_2a, persona: Charlie, title: "When readiness to process cannot recover, it keeps answering not ready", description: "Charlie checks unrecoverable readiness and the harness records persistent not-ready evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.2a", "F26", "readiness_persistent_not_ready", "not-ready-persists", 503)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.2b", fn_name: f26_2b, persona: Charlie, title: "While readiness is not ready, the liveness signal remains separate", description: "Charlie checks liveness during not-ready state and the harness records alive plus not-ready separation evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.2b", "F26", "liveness_maintained_when_not_ready", "alive-while-not-ready", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.2c", fn_name: f26_2c, persona: Charlie, title: "Automatic recovery attempts behind the scenes appear as a marker on the operator screen", description: "Charlie observes recovery attempts and the harness records auto-reconnect marker evidence while readiness remains unchanged.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.2c", "F26", "auto_reconnect_marker", "auto-reconnect-attempting", 503)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.3", fn_name: f26_3, persona: Charlie, title: "The liveness body shows version, uptime, and build marker together", description: "Charlie reads liveness details and the harness records version, uptime, and build marker evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.3", "F26", "liveness_body_markers", "version-uptime-build", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.4", fn_name: f26_4, persona: Charlie, title: "When a notification subscription disconnects and reconnects, it catches up with changes from the gap", description: "Charlie observes subscription reconnection and the harness records catch-up evidence for gap changes.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.4", "F26", "subscription_reconnect_catchup", "gap-catchup", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.5a", fn_name: f26_5a, persona: Charlie, title: "cc-lb announces that it restarted with a clear marker", description: "Charlie views a restart boundary and the harness records clear restart marker evidence.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.5a", "F26", "restart_marker_visible", "restart-boundary", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.5b", fn_name: f26_5b, persona: Charlie, title: "The restart marker remains in audit with time", description: "Charlie records restart audit evidence with timestamp for later chronological review.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.5b", "F26", "restart_marker_audit", "restart-timestamp", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.6", fn_name: f26_6, persona: Charlie, title: "The current number of in-progress calls appears as a gauge on the same screen", description: "Charlie views readiness and the harness records in-progress call gauge evidence with zero marker.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.6", "F26", "in_progress_call_gauge", "current-in-progress", 200)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
    bdd_scenario! { id: "F26.7", fn_name: f26_7, persona: Charlie, title: "During graceful shutdown, liveness and readiness answer separately", description: "Charlie begins graceful shutdown and the harness records alive but not-ready evidence for load balancer behavior.", given: |ctx| { ctx.record_w1_observable(W1ObservableSpec::new("F26.7", "F26", "shutdown_liveness_readiness_split", "alive-not-ready-drain", 503)).await? }, when: |evidence| { evidence }, then: |evidence, ctx| { assert_w1_evidence!(ctx, evidence); }, }
}
