//! Writer stream W4 - platform, audit, and observability.

use cc_lb_bdd_tests::bdd_scenario;

#[path = "support/w4_cost_secret.rs"]
mod w4_cost_secret;
#[path = "support/w4_helpers.rs"]
mod w4_helpers;
#[cfg(feature = "postgres")]
#[path = "support/w4_replica.rs"]
mod w4_replica;
use w4_cost_secret::*;
use w4_helpers::*;
#[cfg(feature = "postgres")]
use w4_replica::*;

mod w4_f13 {
    use super::*;

    bdd_scenario! { id: "F13.1", fn_name: fast_f13_1, persona: Dana, title: "The auditor views one operator's branch changes in chronological order", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.2", fn_name: f13_2, persona: Dana, title: "The audit record contains no secret information on any line", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.3", fn_name: f13_3, persona: Dana, title: "No operator can delete or edit an audit record once it is written", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.4", fn_name: f13_4, persona: Dana, title: "The auditor narrows by time window and page", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.5", fn_name: f13_5, persona: Dana, title: "Only records past the retention period are swept precisely", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.6", fn_name: f13_6, persona: Dana, title: "The start, end, and error of one call are grouped by the same trace marker", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.7", fn_name: f13_7, persona: Dana, title: "Audit records are exported to an external audit system", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.8", fn_name: f13_8, persona: Dana, title: "One call's trace marker is printed in audit, operation logs, and the response", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.9", fn_name: f13_9, persona: Dana, title: "The exported audit file includes tamper evidence", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.10", fn_name: f13_10, persona: Dana, title: "The auditor views all related records for one call in a cross table", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.11", fn_name: f13_11, persona: Dana, title: "Cost and quota violation appear together on the same call line", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F13.12", fn_name: f13_12, persona: Dana, title: "Cost and quota violations are aggregated into the branch report by the same call unit", description: "Dana writes and reads real audit rows through cc-lb storage and the admin audit route, then checks ordering, grouping, redaction, and violation evidence.", given: |ctx| { ctx }, when: |ctx| { w4_audit_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
}

mod w4_f14 {
    use super::*;

    bdd_scenario! { id: "F14.1", fn_name: fast_f14_1, persona: Alice, title: "Saving a draft does not yet affect actual behavior", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.2", fn_name: f14_2, persona: Alice, title: "Validating a draft exposes problems before apply", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.3", fn_name: fast_f14_3, persona: Alice, title: "Invalid configuration is rejected at save time", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.4", fn_name: fast_f14_4, persona: Alice, title: "Only a draft that passed validation is applied", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.5", fn_name: f14_5, persona: Alice, title: "An applied configuration change is recorded as one line in apply history", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.6", fn_name: f14_6, persona: Alice, title: "The operator views apply history in time order", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.7", fn_name: f14_7, persona: Alice, title: "The operator rolls back to a previous configuration version", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.8", fn_name: f14_8, persona: Alice, title: "Items that can apply without restart apply without restart", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.9", fn_name: f14_9, persona: Alice, title: "Items that require restart are marked before apply", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.10", fn_name: f14_10, persona: Alice, title: "The operator downloads the applied configuration as a file", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.11", fn_name: f14_11, persona: Alice, title: "Bootstrap configuration is reflected only once on first boot", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.12", fn_name: f14_12, persona: Alice, title: "Unapplied drafts are automatically cleared after the configured period", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.13", fn_name: f14_13, persona: Alice, title: "Items requiring restart are clearly marked item by item", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F14.14", fn_name: f14_14, persona: Alice, title: "cc-lb notices when the configuration file on disk changes", description: "Alice verifies configuration draft behavior through cc-lb admin routes and storage-backed draft, validation, and history records.", given: |ctx| { ctx }, when: |ctx| { w4_config_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
}

mod w4_f15 {
    use super::*;

    bdd_scenario! { id: "F15.1", fn_name: f15_1, persona: Charlie, title: "New calls are not accepted after the shutdown signal", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.2", fn_name: f15_2, persona: Charlie, title: "Calls already in progress complete even during drain", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.3", fn_name: f15_3, persona: Charlie, title: "When the drain wait time expires, remaining calls are forced to end and reported", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.4", fn_name: f15_4, persona: Charlie, title: "Ongoing streams are not disconnected when a new certificate applies", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.5", fn_name: f15_5, persona: Charlie, title: "Invalid certificates are rejected before apply", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.6", fn_name: f15_6, persona: Charlie, title: "The reason an invalid certificate was rejected is shown to the operator on one line", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.7", fn_name: f15_7, persona: Charlie, title: "Operators are notified before certificate expiration is near", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.8", fn_name: f15_8, persona: Charlie, title: "Temporary debug logging turns off automatically after the configured time", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.9", fn_name: f15_9, persona: Charlie, title: "Shutdown semantics are separated by shutdown signal kind", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.10", fn_name: f15_10, persona: Charlie, title: "Debug logging is enabled only by the configured operation signal", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.11", fn_name: f15_11, persona: Charlie, title: "The operation-only socket rejects access from external callers", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.12", fn_name: f15_12, persona: Charlie, title: "The operation-only socket normally receives management calls from an operator on the same machine", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.13", fn_name: f15_13, persona: Charlie, title: "The external caller port and operation-only socket stay separated during drain", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F15.14", fn_name: f15_14, persona: Charlie, title: "Other replicas retain a marker that one replica completed shutdown", description: "Charlie verifies lifecycle and operation behavior through real health, readiness, admin status, and audit records.", given: |ctx| { ctx }, when: |ctx| { w4_lifecycle_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
}

mod w4_f17 {
    use super::*;

    bdd_scenario! { id: "F17.1", fn_name: fast_f17_1, persona: Charlie, title: "A change on one replica is immediately announced to another replica", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.2", fn_name: f17_2, persona: Charlie, title: "Only one replica among many performs the work - credential warmup", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.3", fn_name: f17_3, persona: Charlie, title: "If the replica performing work disappears, another replica takes over", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.4", fn_name: f17_4, persona: Charlie, title: "All replicas see the same value at the same time for a configuration change", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.5", fn_name: f17_5, persona: Charlie, title: "If two operators try to edit the same line at the same time, only one succeeds", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.6", fn_name: f17_6, persona: Charlie, title: "If two replicas both believe they hold the same lease, only one continues the work", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.7", fn_name: f17_7, persona: Charlie, title: "Lease self-check results remain in operation logs and metrics", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.8", fn_name: f17_8, persona: Charlie, title: "The operator sees which replicas are alive on one screen", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.9", fn_name: f17_9, persona: Charlie, title: "If a replica identifier is damaged, a new identifier is issued safely", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.10", fn_name: f17_10, persona: Charlie, title: "Work tied to the old identifier is handed off to another replica or expires", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.11", fn_name: f17_11, persona: Charlie, title: "The old identifier and new identifier are not used at the same time for the same call", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.12", fn_name: f17_12, persona: Charlie, title: "The same operator scenario produces the same result on two storage backends", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.13", fn_name: f17_13, persona: Charlie, title: "All consistency scenarios pass on both storage backends", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.14", fn_name: f17_14, persona: Charlie, title: "Boot is clearly rejected if the storage backend kind is changed incorrectly", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.15", fn_name: f17_15, persona: Charlie, title: "The same operator action leaves the same number and kinds of audit lines on both storage backends", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.16", fn_name: f17_16, persona: Charlie, title: "Secrets are not visible in plaintext in audit records on either storage backend", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.17", fn_name: f17_17, persona: Charlie, title: "Downgrade migration is rejected at boot", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F17.18", fn_name: f17_18, persona: Charlie, title: "Concurrent edits of the same line by two operators make the same decision on both storage backends", description: "Charlie verifies multi-replica behavior with two BddHarness instances sharing one Postgres schema and storage pool.", backend: postgres_only, given: |ctx| { ctx }, when: |ctx| { w4_replica_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
}

mod w4_f18 {
    use super::*;

    bdd_scenario! { id: "F18.1", fn_name: f18_1, persona: Dana, title: "The operator views current prices by model on one screen", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.2", fn_name: fast_f18_2, persona: Dana, title: "Per-call cost is calculated exactly from catalog prices", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.3", fn_name: f18_3, persona: Dana, title: "The branch cost report aggregates accurately by team", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.4", fn_name: f18_4, persona: Dana, title: "When a price changes, the new price applies starting with new calls after that point", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.5", fn_name: f18_5, persona: Dana, title: "A cache-hit call shows savings as a separate item", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.6", fn_name: f18_6, persona: Dana, title: "Price change history is preserved in time order", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.7", fn_name: f18_7, persona: Dana, title: "Historical call cost calculation matches the price history unit price at that point", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.8", fn_name: f18_8, persona: Dana, title: "The call that first creates a cache and the call that rereads the cache are priced separately", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.9", fn_name: f18_9, persona: Dana, title: "The aggregate of cache creation and reuse unit prices matches the branch report total", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.10", fn_name: f18_10, persona: Dana, title: "When token count cannot be exact, it is shown with an estimated marker", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.11", fn_name: f18_11, persona: Dana, title: "Calls reported as estimates provide a reason record and separate query", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.12", fn_name: f18_12, persona: Dana, title: "Previous usage remains visible after an upstream is renamed", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.13", fn_name: f18_13, persona: Dana, title: "Previous usage is preserved after an upstream is deleted", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.14", fn_name: f18_14, persona: Dana, title: "Usage is aggregated accurately when two upstreams are merged into one", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F18.15", fn_name: f18_15, persona: Dana, title: "The usage report also shows upstream renames", description: "Dana verifies cost and usage behavior with real price catalog cache, audit rows, request events, and cache-cost fields.", given: |ctx| { ctx }, when: |ctx| { w4_cost_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
}

mod w4_f20 {
    use super::*;

    bdd_scenario! { id: "F20.1", fn_name: fast_f20_1, persona: Dana, title: "No stored secret remains as plaintext on disk", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.2", fn_name: f20_2, persona: Dana, title: "Tampering is detected immediately", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.3", fn_name: f20_3, persona: Dana, title: "If the master key disappears, secrets can never be recovered", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.4", fn_name: f20_4, persona: Dana, title: "cc-lb rejects boot itself with an invalid master key", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.5", fn_name: f20_5, persona: Dana, title: "No secret is ever read as plaintext during an invalid-master-key boot attempt", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.6", fn_name: f20_6, persona: Dana, title: "Secrets stored before key rotation are still read after key rotation", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.7", fn_name: f20_7, persona: Dana, title: "Boot is rejected if the master key file permissions are too loose", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.8", fn_name: f20_8, persona: Dana, title: "Values following a known-position pattern for secrets are shown as redacted markers by kind", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.9", fn_name: f20_9, persona: Dana, title: "Secret information appears only as redacted markers even in abnormal termination messages", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.10", fn_name: f20_10, persona: Dana, title: "Master key rotation does not disconnect ongoing calls", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.11", fn_name: f20_11, persona: Dana, title: "Variable values in abnormal termination traces also show secrets only as redacted markers", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.12", fn_name: f20_12, persona: Dana, title: "Known-position secret values are redacted in response headers returned to the caller", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F20.13", fn_name: f20_13, persona: Dana, title: "The same secret stored on different upstreams cannot be decrypted for each other", description: "Dana verifies secret-handling behavior with real AEAD encryption and redacted audit records.", given: |ctx| { ctx }, when: |ctx| { w4_secret_observe(ctx).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
}

mod w4_f24 {
    use super::*;

    bdd_scenario! { id: "F24.1", fn_name: f24_1, persona: Alice, title: "New prices are fetched when the external pricing source is healthy", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F24.2", fn_name: f24_2, persona: Alice, title: "The last prices are still used when the external pricing source has a temporary failure", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F24.3", fn_name: f24_3, persona: Alice, title: "The operator is alerted when the external pricing source stays down for a long time", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F24.4", fn_name: f24_4, persona: Alice, title: "After three pricing source failures, disk-stored prices are used or cost reporting is held", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F24.5", fn_name: f24_5, persona: Alice, title: "If the whole pricing catalog is damaged, that fact is reported safely", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F24.6", fn_name: f24_6, persona: Alice, title: "The operator views the last refresh time of the pricing catalog", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F24.7", fn_name: f24_7, persona: Alice, title: "New prices are not used if the pricing catalog provenance proof does not match", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
    bdd_scenario! { id: "F24.8", fn_name: f24_8, persona: Alice, title: "Calls to models absent from the catalog are reported using the configured fallback method", description: "Alice verifies price-catalog dependency behavior with a loopback WireMock source and the persisted price snapshot cache.", given: |ctx| { (ctx, mock_price_source().await) }, when: |pair| { let (ctx, source) = pair; w4_price_catalog_observe(ctx, &source).await? }, then: |result, ctx| { assert_w4_observation(result, ctx); }, }
}
