[package]
name = "cc-lb-storage-redb"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
base64.workspace = true
cc-lb-pricing = { path = "../cc-lb-pricing" }
chacha20poly1305.workspace = true
redb.workspace = true
ring.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
